In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [3]:
type(a)

numpy.ndarray

operations

In [4]:
# addition ,substraction and multiplication
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [5]:
#  creation of 2D array 
a2 = np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [6]:
# creating 3d array 
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [7]:
# to check shape of a2
print(a2.shape)

(2, 3)


In [8]:
# to check shape of a3
print(a3.shape)

(3, 2, 3)


In [9]:
# to check dimension
print(a2.ndim)
print(a3.ndim)

2
3


In [10]:
print(a2.dtype)

int64


In [11]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [12]:

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [14]:
# random lib. used to create 2d array
np.random.randint(1,11,size=(2,3))

array([[ 6,  5,  1],
       [10,  5,  7]], dtype=int32)

In [15]:
# random lib. used to create 3d array
np.random.randint(1,11,size=(3,2,3))

array([[[ 6, 10,  6],
        [ 3,  8,  1]],

       [[ 3,  2,  4],
        [10,  4,  7]],

       [[ 9,  4,  6],
        [ 1,  4,  8]]], dtype=int32)

In [16]:
x = np.random.randint(1,21,size=(2,2))
y =np.random.randint(1,21,size=(2,2))
print(x)
print(y)

[[17 17]
 [15  5]]
[[18  1]
 [20 11]]


In [17]:
print(x+y)
print(x-y)
print(x*y)

[[35 18]
 [35 16]]
[[-1 16]
 [-5 -6]]
[[306  17]
 [300  55]]


In [18]:
# matrix multilication
# 1srt method
print(x @ y)

[[646 204]
 [370  70]]


In [19]:
# 2nd method
np.dot(x,y)

array([[646, 204],
       [370,  70]], dtype=int32)

In [20]:
# product of all elements in the matrix
x.prod()

np.int64(21675)

In [21]:
# mean
x.mean()


np.float64(13.5)

In [22]:
y.mean()

np.float64(12.5)

In [23]:
print(x)

[[17 17]
 [15  5]]


In [24]:
# column wise mean
b= x.mean(axis=0) # column wise
print(b)

[16. 11.]


In [25]:
# row wise mean
c= x.mean(axis=1) # row wise
print(c)

[17. 10.]


In [26]:
# operations
print(x.sum())
print(x.std()) # standard deviation
print(x.var()) # variance

54
4.9749371855331
24.75


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))
print(np.percentile(arr,80))

5.0
3.0
7.0
7.4


In [28]:
arr2 = np.random.randint(11,100,size=(4,4))
print(arr2)

[[46 79 70 42]
 [46 87 31 95]
 [45 50 51 13]
 [34 53 16 85]]


In [29]:
# reshape method
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[46 79 70 42 46 87 31 95]
 [45 50 51 13 34 53 16 85]]
8x2
[[46 79]
 [70 42]
 [46 87]
 [31 95]
 [45 50]
 [51 13]
 [34 53]
 [16 85]]


In [30]:
print(arr2)

[[46 79 70 42]
 [46 87 31 95]
 [45 50 51 13]
 [34 53 16 85]]


In [33]:
# Indexing
print(arr2[0])   # 0th row
print(arr2[0,1]) # 0 row 1st index element 
print(arr2[-1])  # last row

[46 79 70 42]
79
[34 53 16 85]


In [38]:
# slicing
print(arr2[:3]) # oth to 2nd row
print(arr[1:])  #  1st to last row

[[46 79 70 42]
 [46 87 31 95]
 [45 50 51 13]]
[2 3 4 5 6 7 8 9]


In [39]:
# conditions
arr2 > 50

array([[False,  True,  True, False],
       [False,  True, False,  True],
       [False, False,  True, False],
       [False,  True, False,  True]])

In [41]:
y = arr2[arr2<50]
z = y.reshape(4,2)
print(z)

[[46 42]
 [46 31]
 [45 13]
 [34 16]]
