In [3]:
import numpy as np

In [5]:
a = np.array([1,2,3,4,5])
b = np.array([5,4,3,2,1])
print(a)
print(b)

[1 2 3 4 5]
[5 4 3 2 1]


In [6]:
type(a)

numpy.ndarray

operations

In [7]:
# addition ,substraction and multiplication
print(a+b)
print(a-b)
print(a*b)

[6 6 6 6 6]
[-4 -2  0  2  4]
[5 8 9 8 5]


In [8]:
#  creation of 2D array 
a2 = np.array([[1,2,3,],[4,5,6]])
print(a2)

[[1 2 3]
 [4 5 6]]


In [10]:
# creating 3d array 
a3 = np.array([[[1,2,3],[4,5,6]],
               [[7,8,9],[10,11,12]],
               [[13,14,15],[16,17,18]]])
print(a3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [11]:
# to check shape of a2
print(a2.shape)

(2, 3)


In [12]:
# to check shape of a3
print(a3.shape)

(3, 2, 3)


In [15]:
# to check dimension
print(a2.ndim)
print(a3.ndim)

2
3


In [16]:
print(a2.dtype)

int64


In [19]:
np.arange(11)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:

np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
# random lib. used to create 2d array
np.random.randint(1,11,size=(2,3))

array([[ 1,  6,  7],
       [10,  7,  6]], dtype=int32)

In [24]:
# random lib. used to create 3d array
np.random.randint(1,11,size=(3,2,3))

array([[[ 2, 10,  2],
        [ 6, 10,  5]],

       [[ 5,  1,  9],
        [ 8,  3,  3]],

       [[ 9,  9, 10],
        [ 2,  5,  8]]], dtype=int32)

In [25]:
x = np.random.randint(1,21,size=(2,2))
y =np.random.randint(1,21,size=(2,2))
print(x)
print(y)

[[ 7 13]
 [ 9  2]]
[[ 1  5]
 [14 12]]


In [26]:
print(x+y)
print(x-y)
print(x*y)

[[ 8 18]
 [23 14]]
[[  6   8]
 [ -5 -10]]
[[  7  65]
 [126  24]]


In [27]:
# matrix multilication
# 1srt method
print(x @ y)

[[189 191]
 [ 37  69]]


In [28]:
# 2nd method
np.dot(x,y)

array([[189, 191],
       [ 37,  69]], dtype=int32)

In [29]:
# product of all elements in the matrix
x.prod()

np.int64(1638)

In [32]:
# mean
x.mean()


np.float64(7.75)

In [33]:
y.mean()

np.float64(8.0)

In [36]:
print(x)

[[ 7 13]
 [ 9  2]]


In [34]:
# column wise mean
b= x.mean(axis=0) # column wise
print(b)

[8.  7.5]


In [35]:
# row wise mean
c= x.mean(axis=1) # row wise
print(c)

[10.   5.5]


In [37]:
# operations
print(x.sum())
print(x.std()) # standard deviation
print(x.var()) # variance

31
3.960744879438715
15.6875


In [42]:
arr = np.array([1,2,3,4,5,6,7,8,9])
print(np.percentile(arr,50))
print(np.percentile(arr,25))
print(np.percentile(arr,75))
print(np.percentile(arr,80))

5.0
3.0
7.0
7.4


In [43]:
arr2 = np.random.randint(11,100,size=(4,4))
print(arr2)

[[21 79 64 33]
 [61 34 67 71]
 [48 14 55 28]
 [83 44 49 14]]


In [47]:
# reshape method
print('2x8')
print(arr2.reshape(2,8))
print('8x2')
print(arr2.reshape(8,2))

2x8
[[21 79 64 33 61 34 67 71]
 [48 14 55 28 83 44 49 14]]
8x2
[[21 79]
 [64 33]
 [61 34]
 [67 71]
 [48 14]
 [55 28]
 [83 44]
 [49 14]]
